language: php

services:
  - docker

notifications:
  email:
    on_success: never

php:
  - 7.2
  - 7.3
  - 5.6

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n

script:
  - composer test -- --coverage-clover=coverage.xml

jobs:
  include:
    - stage: PHPQA Code Quality
      script:
        - docker run --rm -u $UID -v $PWD:/app eko3alpha/docker-phpqa --report --ignoredDirs vendor
after_success:
- bash <(curl -s https://codecov.io/bash)
