language: php

services:
  - docker

notifications:
  email:
    on_success: never

php:
  - 7.2
  - 7.3
  - 5.6


matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install -n

script:
  - composer test -- --coverage-clover=coverage.xml

jobs:
  include:
    - stage: PHP CS Fixer
      script:
        - ./vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`
    - stage: PHPStan Code quality
      script:
        - composer require --dev "phpstan/phpstan:^0.10" --ignore-platform-reqs && composer phpstan
    - stage: PHPQA Full analysis
      script:
        - docker build -t prestashop/phpqa .
        - docker run --rm -u $UID -v $PWD:/app prestashop/phpqa --report --ignoredDirs vendor
after_success:
- bash <(curl -s https://codecov.io/bash)
